selenium-chrome-driver: upgrade to 2.36
agabrys/chocolatey-packages pull request #18
Opened 2018-03-20 12:42 UTC by vtintillier

2018-03-20 12:45 UTC, vtintillier commented
Hello @agabrys . We need 2.37 as 2.36 is blocked as Trojan (!) by McAfee...

Thanks

2018-03-21 07:38 UTC, agabrys requested changes
The checksum is incorrect.

2018-03-21 07:38 UTC, agabrys commented on manual/selenium-chrome-driver/x86/tools/chocolateyInstall.ps1
> +  checksum      = '947ed273fa498ccb5e14dba511d2b2ab0e40fa6ff273af631471402c8aadb01cb921d27c00e9ee87db3744f257745525067113cedf3de9c7c71a2d5a57556fd6'
A correct checksum of the file is:
`189f1942161f8696ac79b26eb20712c6c797e58a4c83081584e182eda6213ff325bc385675c733207f655cd858d5b737ce86c7574c258ab2700955438979c003`

Maybe they overwrote `chromedriver_win32.zip` file after you had prepared the PR.

2018-03-21 07:39 UTC, agabrys commented
I updated the package, see: 265c890a4a65c10856feff5da8daaff3e5ba438a

2018-03-21 07:39 UTC, closed without merging

2018-03-21 07:55 UTC, vtintillier commented
Thank you @agabrys . I now realize I checksummed the exe file, not the zip 😞